research_task:
  description: >
    Hunt down the freshest, most badass info on {topic}. Year is {current_year}, so keep it spicy and current.
    Prioritize finding up-to-date platforms, apps, or services that readers can use TODAY to get started.
  expected_output: >
    A list of 10 bullet points packed with relevance, wit, and just enough sass to keep it interesting.
  agent: researcher

reporting_task:
  description: >
    Expand each point into a full, juicy section of the report. Write like you’re selling the dream — hype, humor, and hard facts.
    Most importantly, include clear, actionable first steps that a reader can start doing TODAY to make real money.
  expected_output: >
    A markdown report, no code blocks, dripping with motivation, cheeky wisdom, sarcastic commentary, and step-by-step beginner actions.
  agent: reporting_analyst
